name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install package
        run: pip install .

      - name: Analyze test image
        run: |
          mkdir -p outputs
          hipjsw docs/images/Medical_X-Ray_imaging_SAL07_nevit.jpg --output-plots outputs/plot-{scan_id}.png --output-json outputs/test.json --output-csv outputs/test.csv --print-json
